In [69]:
import pandas as pd
import numpy as np
import catboost
from catboost import CatBoostRegressor
from xgboost import XGBRegressor
import xgboost
print("Using CatBoost version",catboost.__version__)
print("Using XGBoost version",xgboost.__version__)
import sklearn
print(sklearn.__version__)
from sklearn.metrics import mean_squared_log_error, make_scorer
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor,GradientBoostingRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.preprocessing import LabelEncoder,OrdinalEncoder
from sklearn.svm import SVR
from sklearn.linear_model import SGDRegressor
from sklearn.decomposition import PCA
from sklearn.model_selection import cross_val_score,KFold
from sklearn import set_config
set_config(display='text')
import warnings
warnings.filterwarnings("ignore")

Using CatBoost version 1.2.7
Using XGBoost version 2.1.3
1.6.1

In [3]:
train_df = pd.read_csv("train_molecular.csv")
train_df.head()

,Batch_ID,T80,Smiles,Mass,HAcceptors,HDonors,LogP,Asphericity,Rg,TPSA,...,SDOS4.5,SDOS4.6,SDOS4.7,SDOS4.8,SDOS4.9,SDOS5.0,SDOS5.1,SDOS5.2,SDOS5.3,SDOS5.4
0,Train-01,103.86,CCCCCCCCCCCCc1ccsc1-c1ccc(-c2cccs2)cc1,410.692,2,0,9.6070,0.301361,5.187321,0.00,...,1.717761,1.970186,1.760071,1.224983,0.664733,0.282353,0.096763,0.034589,0.030793,0.057340
1,Train-02,101.13,CCCCCCCCCCCCc1ccsc1-c1cccs1,334.594,2,0,7.9400,0.367472,4.141425,0.00,...,0.012396,0.046031,0.133124,0.299840,0.525958,0.718549,0.764711,0.634854,0.414866,0.225909
2,Train-03,78.30,CN1CCN(S(=O)(=O)c2ccc(-c3ccc(-c4cccs4)cc3)cc2)CC1,398.553,4,0,4.0182,0.799589,5.368024,40.62,...,2.421162,2.703267,2.352276,1.595867,0.845839,0.354620,0.127878,0.060600,0.064782,0.098908
3,Train-04,71.88,O=C1c2ccccc2C(=O)c2cc(-c3ccc(-c4cccs4)s3)ccc21,372.470,4,0,5.9190,0.793825,4.948903,34.14,...,0.886320,0.579059,0.345148,0.246564,0.276259,0.381997,0.495304,0.566935,0.594203,0.614075
4,Train-05,68.37,CC(C)(C)OC(=O)n1ccc2ccc(-c3ccc(-c4ccc(-c5cccs5...,457.620,5,0,8.5485,0.671148,5.994751,31.23,...,0.487723,0.245764,0.249019,0.363222,0.474953,0.505358,0.440671,0.330129,0.234649,0.183111

In [5]:
print(train_df.shape)
train_df.isnull().sum().sort_values(ascending=False).head(20)

(42, 146)

Batch_ID    0
TDOS4.1     0
TDOS2.5     0
TDOS2.6     0
TDOS2.7     0
TDOS2.8     0
TDOS2.9     0
TDOS3.0     0
TDOS3.1     0
TDOS3.2     0
TDOS3.3     0
TDOS3.4     0
TDOS3.5     0
TDOS3.6     0
TDOS3.7     0
TDOS3.8     0
TDOS3.9     0
TDOS2.4     0
TDOS2.3     0
TDOS2.2     0
dtype: int64

In [7]:
display(train_df["Smiles"].info())

<class 'pandas.core.series.Series'>
RangeIndex: 42 entries, 0 to 41
Series name: Smiles
Non-Null Count  Dtype
--------------  -----
42 non-null     object
dtypes: object(1)
memory usage: 468.0+ bytes

None

In [9]:
X = train_df.drop(columns=['Batch_ID','T80','Smiles'],axis=1)
y = train_df["T80"]

In [11]:
models = {
    "RandomForest":RandomForestRegressor(max_depth=5,n_estimators=10_000,verbose=0),
    "GradienBoosting":GradientBoostingRegressor(max_depth=5,n_estimators=10_000,verbose=0),
    "Support Vector Regression":SVR(kernel="rbf",C=100,verbose=0,gamma="scale",epsilon=0.01),
    "SGDR":SGDRegressor(loss='huber',random_state=700,early_stopping=True,epsilon=0.001)}

In [43]:
msle_scorer = make_scorer(mean_squared_log_error, greater_is_better=False)
skf = KFold(n_splits=10, shuffle=True, random_state=700)
y_log = np.log1p(y)

In [83]:
for name, model in models.items():
    # cross_val_score will return negative MSLE scores because we set 
    # greater_is_better=False above
    scores = cross_val_score(
        model,
        X,
        y,
        cv=skf.split(X, y_log),  # custom split with StratifiedKFold
        scoring=msle_scorer
    )
    
    # Convert negative MSLE to positive MSLE
    msle_values = -scores
    print(f"Model {name}:")
    print(f"    -> Fold scores (MSLE): {msle_values}")
    print(f"    -> Average MSLE       : {msle_values.mean():.6f}\n")

Model RandomForest:
    -> Fold scores (MSLE): [1.38912192 0.24055317 0.58847899 2.14226188 1.38519822]
    -> Average MSLE       : 1.149123

Model GradienBoosting:
    -> Fold scores (MSLE): [0.67622012 0.50066656 0.93261704 2.78479608 2.59057591]
    -> Average MSLE       : 1.496975

Model Support Vector Regression:
    -> Fold scores (MSLE): [1.02020037 0.37806305 0.40927181 2.11020328 0.70704823]
    -> Average MSLE       : 0.924957

Model SGDR:
    -> Fold scores (MSLE): [2.50149489 0.96912467 1.7009263  1.16633208 1.5899594 ]
    -> Average MSLE       : 1.585567

In [97]:
kf = KFold(n_splits=5,shuffle=True,random_state=700)
cat = CatBoostRegressor(
        max_depth=5,  
        random_seed=420, 
        subsample=1,
        loss_function='RMSE',
        eval_metric='MSLE',
        n_estimators=10_0000,  
        learning_rate=0.009, 
        verbose=0,
        early_stopping_rounds=10
    )
scores_cat = cross_val_score(cat,X,y_log,cv=kf,scoring=msle_scorer)
msle_values_cat = -scores_cat
print(f"fold msle for catboost : {msle_values_cat}")
print(f"average msle for catboost : {msle_values_cat.mean():.4f}")

fold msle for catboost : [0.09882327 0.02548201 0.04088658 0.11113048 0.09390963]
average msle for catboost : 0.0740

In [107]:
neigh = KNeighborsRegressor(n_neighbors=14,leaf_size=100,p=3,n_jobs=15,weights='uniform')
scores_neigh = cross_val_score(neigh,X,y_log,cv=skf,scoring=msle_scorer)
msle_values_neigh = -scores_neigh
print(f"fold msle for KNNeighbors : {msle_values_neigh}")
print(f"average msle for KNNeighbors : {msle_values_neigh.mean():.4f}")
neigh.fit(X,y_log)

fold msle for KNNeighbors : [0.09976955 0.05556598 0.02865283 0.05458327 0.04816552 0.03051737
 0.13181339 0.15529679 0.04052376 0.07880778]
average msle for KNNeighbors : 0.0724

KNeighborsRegressor(leaf_size=100, n_jobs=15, n_neighbors=14, p=3)

In [89]:
cat.fit(X,y)

In [87]:
test_df = pd.read_csv("test_molecular.csv")

X_test = test_df.drop(columns=['Batch_ID','T80','Smiles'])
# --- 4) Predict with your trained CatBoostRegressor instance (cat_model) ---
y_pred = neigh.predict(X_test)

In [89]:
mole_df = pd.DataFrame({"Batch_ID":test_df["Batch_ID"],"T80":y_pred})
display(mole_df)
mole_df.to_csv("submission_mole.csv",index=False)

  Batch_ID       T80
0  Test-01  3.259932
1  Test-02  2.999859
2  Test-03  3.259932
3  Test-04  2.999859
4  Test-05  2.827606
5  Test-06  3.259932
6  Test-07  3.259932
7  Test-08  3.259932
8  Test-09  2.693299

In [37]:
test_df

,Batch_ID,T80,Smiles,Mass,HAcceptors,HDonors,LogP,Asphericity,Rg,TPSA,...,SDOS4.5,SDOS4.6,SDOS4.7,SDOS4.8,SDOS4.9,SDOS5.0,SDOS5.1,SDOS5.2,SDOS5.3,SDOS5.4
0,Test-01,NaN,COC(=O)c3ccc(c2ccc(c1ccco1)cc2)s3,284.336,4,0,4.4617,0.796737,4.323524,39.44,...,0.709932,0.266678,0.078569,0.020244,0.011813,0.025880,0.061288,0.118430,0.181805,0.220200
1,Test-02,NaN,CCCCCCc2c(CCCCCC)c(c1cccs1)sc2c3ccc(C(=O)OC)cc3,468.728,4,0,9.1758,0.268870,5.019005,26.30,...,1.913133,1.823127,1.356344,0.797689,0.399819,0.236639,0.250003,0.343148,0.426963,0.445557
2,Test-03,NaN,COC(=O)c3ccc(c2ccc(c1cccc(OC)c1)cc2)s3,324.401,4,0,4.8773,0.846029,4.976660,35.53,...,2.302484,1.460937,0.729424,0.299914,0.124335,0.079533,0.080611,0.097277,0.129095,0.178570
3,Test-04,NaN,CCCCCCc3csc(c2ccc(c1ccc(C(=O)OC)s1)cc2)c3CCCCCC,468.728,4,0,9.1758,0.654627,5.609674,26.30,...,1.861847,1.032900,0.447376,0.154937,0.054493,0.048734,0.094820,0.181653,0.293166,0.390163
4,Test-05,NaN,CCCCCCc1ccsc1c3cc(CCCCCC)c(c2sccc2CCCCCC)s3,500.883,3,0,11.5735,0.406478,5.526453,0.00,...,0.432056,0.166929,0.051487,0.016869,0.017613,0.040848,0.094981,0.197741,0.356762,0.543620
5,Test-06,NaN,c4ccc3c(c1ccncc1)ccc(c2ccncc2)c3c4,282.346,2,0,4.9638,0.533503,3.743344,25.78,...,0.777461,1.066911,1.140554,0.950557,0.619796,0.322005,0.148311,0.097106,0.141809,0.270638
6,Test-07,NaN,c4cc(c2ccc(c1ccncc1)c3nsnc23)ccn4,292.367,5,0,3.1617,0.477945,3.506304,51.56,...,0.000012,0.000092,0.000558,0.002758,0.011183,0.037205,0.101123,0.223117,0.397414,0.570078
7,Test-08,NaN,c3cc(c2ccc(c1ccncc1)s2)ccn3,238.315,3,0,3.8721,0.749892,3.629240,25.78,...,1.384438,0.755842,0.325354,0.119390,0.056951,0.062667,0.098769,0.146215,0.184803,0.196689
8,Test-09,NaN,CCCCCCc2c(CCCCCC)c(c1cccc(OC)c1)sc2c3ccc(C(=O)...,492.725,4,0,9.1229,0.269112,5.146173,35.53,...,1.635836,1.974697,1.866746,1.399961,0.869828,0.510805,0.368140,0.373142,0.442061,0.503521

In [71]:
train_df

,Batch_ID,T80,Smiles,Mass,HAcceptors,HDonors,LogP,Asphericity,Rg,TPSA,...,SDOS4.5,SDOS4.6,SDOS4.7,SDOS4.8,SDOS4.9,SDOS5.0,SDOS5.1,SDOS5.2,SDOS5.3,SDOS5.4
0,Train-01,103.86,CCCCCCCCCCCCc1ccsc1-c1ccc(-c2cccs2)cc1,410.692,2,0,9.60700,0.301361,5.187321,0.00,...,1.717761,1.970186,1.760071,1.224983,0.664733,0.282353,0.096763,0.034589,0.030793,0.057340
1,Train-02,101.13,CCCCCCCCCCCCc1ccsc1-c1cccs1,334.594,2,0,7.94000,0.367472,4.141425,0.00,...,0.012396,0.046031,0.133124,0.299840,0.525958,0.718549,0.764711,0.634854,0.414866,0.225909
2,Train-03,78.30,CN1CCN(S(=O)(=O)c2ccc(-c3ccc(-c4cccs4)cc3)cc2)CC1,398.553,4,0,4.01820,0.799589,5.368024,40.62,...,2.421162,2.703267,2.352276,1.595867,0.845839,0.354620,0.127878,0.060600,0.064782,0.098908
3,Train-04,71.88,O=C1c2ccccc2C(=O)c2cc(-c3ccc(-c4cccs4)s3)ccc21,372.470,4,0,5.91900,0.793825,4.948903,34.14,...,0.886320,0.579059,0.345148,0.246564,0.276259,0.381997,0.495304,0.566935,0.594203,0.614075
4,Train-05,68.37,CC(C)(C)OC(=O)n1ccc2ccc(-c3ccc(-c4ccc(-c5cccs5...,457.620,5,0,8.54850,0.671148,5.994751,31.23,...,0.487723,0.245764,0.249019,0.363222,0.474953,0.505358,0.440671,0.330129,0.234649,0.183111
5,Train-06,51.70,c1csc(-c2ccc(-c3ccc(-c4ccc5c(c4)C4(c6ccccc6Oc6...,572.754,3,0,11.27940,0.579470,5.999279,9.23,...,0.341195,0.334334,0.404439,0.437977,0.406705,0.343641,0.292732,0.277376,0.303196,0.365520
6,Train-07,48.00,CC(C)(C)OC(=O)CN1C(=O)CCc2cc(-c3ccc(-c4cccs4)s...,425.575,5,0,5.76450,0.692029,5.358738,46.61,...,0.573623,0.218337,0.074412,0.037166,0.039435,0.053866,0.070479,0.083547,0.092867,0.108030
7,Train-08,44.96,Cc1cc(-c2ccc(-c3ccc(-c4cccs4)s3)cc2)c2nnnn2c1,374.494,6,0,5.55672,0.761473,5.110443,43.08,...,0.159368,0.114065,0.150824,0.197677,0.214038,0.194934,0.164543,0.147707,0.149024,0.161365
8,Train-09,38.74,CCCCCCCCCCCCc1ccsc1-c1ccc(-c2ccc(-c3ccc(-c4ccc...,580.975,5,0,13.12550,0.265031,6.364666,0.00,...,0.308259,0.392212,0.399284,0.329140,0.241205,0.195217,0.202376,0.233241,0.264707,0.314958
9,Train-10,32.17,Cc1ccc(-c2ccc(-c3ccc(-c4cccs4)s3)cc2)cc1Cc1ccc...,522.735,3,0,10.57742,0.718782,6.970584,0.00,...,0.501778,0.465954,0.789773,1.303114,1.732565,1.817389,1.514204,1.028088,0.614496,0.391702
10,Train-11,31.94,CC(NC(=O)OC(C)(C)C)c1ccc(-c2ccc(-c3ccc(-c4cccs...,467.681,5,1,8.45780,0.700124,6.262056,38.33,...,0.015415,0.014004,0.024370,0.037490,0.047134,0.051700,0.057204,0.072323,0.099877,0.137648
11,Train-12,24.91,c1ccc([Si](c2ccccc2)(c2ccccc2)c2cccc(-c3ccc(-c...,582.891,3,0,8.24950,0.626843,6.161435,0.00,...,0.047649,0.021793,0.029982,0.049261,0.066700,0.073770,0.072121,0.073487,0.089060,0.121592
12,Train-13,23.09,CCCCC(CC)COc1c2cc(-c3ccc4oc(-c5ccc(N(c6ccccc6)...,806.150,6,0,16.85640,0.538961,7.934825,34.84,...,1.100114,1.197390,1.258619,1.169634,1.030111,1.053577,1.376164,1.899762,2.306988,2.294971
13,Train-14,19.48,CC(C)(C)c1ccc(-c2ccc(C(C)(C)C)cc2-c2cc3sc(-c4c...,568.898,4,0,12.34880,0.434159,5.791845,0.00,...,0.184934,0.069611,0.065651,0.114596,0.191226,0.280472,0.378332,0.497326,0.657729,0.869030
14,Train-15,15.64,Cc1ccc(NC(=O)OC(C)(C)C)cc1-c1cc2sc(-c3ccc(-c4c...,509.743,6,1,9.74222,0.787604,6.572627,38.33,...,0.061908,0.104109,0.187088,0.279792,0.340863,0.340609,0.290044,0.241399,0.259636,0.392452
15,Train-16,15.00,CCCCC(CC)COc1c2cc(-c3cccc(-c4c5ccccc5c(-c5cccc...,825.196,4,0,17.76700,0.377106,6.893407,18.46,...,1.276163,1.236475,1.106500,0.917993,0.784858,0.798003,0.968787,1.232609,1.494547,1.732633
16,Train-17,10.88,CCCCC(CC)COc1c2cc(-c3ccc4oc(-c5ccc6[nH]c(-c7cc...,772.064,5,1,15.67400,0.544806,7.843849,47.39,...,3.765836,2.986408,2.431030,2.394081,2.738119,3.060757,3.103451,2.908210,2.608173,2.239389
17,Train-18,10.80,c1ccc(C(c2ccccc2)(c2ccccc2)n2cnc(-c3ccc(-c4ccc...,550.752,4,0,9.84730,0.641686,6.158710,17.82,...,0.278243,0.084429,0.033286,0.041325,0.074904,0.115364,0.144332,0.153149,0.152028,0.159214
18,Train-19,10.60,CCCCC(CC)COc1c2cc(-c3ccc(-c4nc(C#N)cs4)[se]3)s...,683.867,7,0,11.02558,0.239870,5.712218,55.14,...,0.092371,0.102275,0.183105,0.322816,0.477563,0.581964,0.599983,0.563233,0.538207,0.550405
19,Train-20,10.49,CCCCC(CC)COc1c2cc(-c3ccc4oc(-c5cccc([Si](c6ccc...,897.335,5,0,14.76400,0.465648,7.993211,31.60,...,2.987607,2.634822,2.217800,1.917626,1.798253,1.778342,1.780706,1.789721,1.749091,1.555005
20,Train-21,10.48,Cc1cc(N2CCN(C)CC2)ncc1-c1cc2sc(-c3ccc(-c4cccs4...,493.748,7,0,7.54202,0.895896,6.585754,19.37,...,0.227512,0.296530,0.341776,0.345605,0.339209,0.359822,0.414977,0.483200,0.535477,0.556691
21,Train-22,9.77,CCCCC(CC)COc1c2cc(-c3ccc4oc(-c5ccc6c(c5)CCC(=O...,822.146,8,0,14.00750,0.492387,7.961364,78.21,...,3.038373,2.355654,1.780402,1.423525,1.233487,1.164592,1.242051,1.434817,1.585311,1.548261
22,Train-23,9.70,CCCCC(CC)COc1c2cc(-c3cccc(-c4cc(OCc5ccccc5)cc(...,811.166,6,0,15.79840,0.368961,7.193270,36.92,...,1.288984,1.212146,1.025744,0.770313,0.590080,0.627491,0.953214,1.536687,2.216203,2.722389
23,Train-24,9.30,CCCCC(CC)COc1c2cc(-c3cccc(N4CCCC4)c3C=O)sc2c(O...,619.937,6,0,11.38610,0.223243,5.437466,38.77,...,0.410386,0.400238,0.395207,0.388465,0.415012,0.527604,0.768673,1.153479,1.617136,1.972439
24,Train-25,9.15,CCCCC(CC)COc1c2cc(-c3ccc4oc(-c5cnc(N6CCN(C)CC6...,752.103,8,0,12.84182,0.504757,7.550930,50.97,...,3.487792,2.536978,1.830117,1.427646,1.202722,1.086964,1.125558,1.314435,1.497989,1.498365
25,Train-26,8.87,Cc1cc(N2CCN(C)CC2)ncc1-c1ccc(-c2ccc(-c3ccc(-c4...,519.786,7,0,8.05582,0.913014,7.152631,19.37,...,0.157677,0.182028,0.210050,0.263461,0.346355,0.427601,0.460674,0.427748,0.360274,0.316230
26,Train-27,8.64,CCCCCCCCCCCCc1ccsc1-c1cc2sc(-c3ccc(-c4cccs4)s3...,554.937,5,0,12.61170,0.447059,6.613980,0.00,...,0.076989,0.116769,0.188987,0.258558,0.297906,0.298235,0.273187,0.248287,0.247886,0.288029
27,Train-28,7.86,CCCCCCCCCCCCc1ccsc1-c1ccc(-c2ccc(-c3cccs3)s2)[...,545.741,3,0,10.39250,0.738241,6.419824,0.00,...,0.131019,0.090671,0.128171,0.195201,0.265441,0.323544,0.358051,0.365439,0.365806,0.397517
28,Train-29,6.67,CC(C)(C)OC(=O)N1CCc2nc(-c3ccc(-c4ccc(-c5cccs5)...,480.680,6,0,7.56030,0.896650,6.737175,42.43,...,0.102192,0.053905,0.057559,0.066875,0.065757,0.056637,0.049996,0.052534,0.064215,0.086310
29,Train-30,5.34,CCCCC(CC)COc1c2cc(-c3ccc(C=CC(=O)O)cc3F)sc2c(O...,610.857,5,1,11.21030,0.252755,5.635940,55.76,...,0.916607,0.601741,0.442480,0.504168,0.727710,0.949016,0.999768,0.836149,0.568627,0.353141
30,Train-31,5.00,COc1ccc(CNc2ccc([N+](=O)[O-])cc2-c2cccc(-c3ccc...,498.629,6,1,8.33950,0.571002,5.799953,64.40,...,1.055306,0.529320,0.269694,0.172742,0.182909,0.285081,0.445000,0.585900,0.632279,0.572550
31,Train-32,5.00,CCCCC(CC)COc1c2cc(-c3cccc(S(=O)(=O)N4CCC4)c3)s...,641.965,6,0,10.36780,0.169945,5.578843,55.84,...,1.087565,1.046183,0.886585,0.635332,0.431613,0.414506,0.639305,1.036501,1.409758,1.539377
32,Train-33,4.80,CCCCC(CC)COc1c2cc(-c3ccc4oc(-c5c(C(=O)OCC)[nH]...,750.039,7,1,14.04460,0.337807,6.837853,73.69,...,1.079127,1.004750,0.984228,0.898034,0.793240,0.848619,1.253099,2.013493,2.818927,3.188643
33,Train-34,3.50,CCCCC(CC)COc1c2cc(-c3cccc(-c4cc(S(=O)(=O)O)c(N...,824.099,9,2,12.24470,0.216878,6.504371,132.99,...,1.600296,1.480978,1.177862,0.835696,0.666518,0.792678,1.177938,1.647333,1.998530,2.151596
34,Train-35,3.00,CCCCC(CC)COc1c2cc(-c3ccc(-c4ccc(-c5ccc(Nc6ncnc...,1005.426,12,1,16.98550,0.788372,10.519416,77.97,...,0.270939,0.206019,0.182727,0.214332,0.289777,0.386628,0.489971,0.605995,0.754179,0.941366
35,Train-36,2.42,CCCCC(CC)COc1c2cc(-c3ccc(-c4ccc(C)s4)[se]3)sc2...,671.896,5,0,12.06732,0.246241,5.789809,18.46,...,0.075328,0.061237,0.090979,0.157469,0.238350,0.304021,0.342322,0.369794,0.406149,0.442678
36,Train-37,2.36,c1ccc(-c2c3ccccc3c(-c3ccc(-c4cccs4)s3)c3ccccc2...,418.586,2,0,9.11700,0.548416,4.551723,0.00,...,0.942892,1.173117,1.195886,0.990336,0.662650,0.361304,0.183158,0.169251,0.378366,0.938064
37,Train-38,1.90,CCCCC(CC)COc1c2cc(-c3ccc(-c4cc(N)c(N)c(C(=O)OC...,693.013,9,2,11.65290,0.264937,6.316720,96.80,...,0.246690,0.132213,0.073825,0.065101,0.101151,0.185995,0.316489,0.468792,0.620058,0.780497
38,Train-39,1.50,CCCCC(CC)COc1c2cc(-c3ccc(-c4ccc(-c5cc(-c6csc(C...,814.242,9,0,15.87092,0.514596,7.547894,40.58,...,0.106219,0.105615,0.150703,0.252149,0.437196,0.716799,1.034483,1.268764,1.315597,1.178618
39,Train-40,1.50,CCCCC(CC)COc1c2cc(-c3cc4sc(-c5ccc(S(=O)(=O)NCC...,883.302,10,2,13.71960,0.655398,8.646811,102.96,...,0.197899,0.219929,0.282535,0.331491,0.336168,0.313300,0.296641,0.293509,0.286642,0.269778
40,Train-41,4.38,c3cc(c2ccc(c1ccncc1)s2)ccn3,238.315,3,0,3.87210,0.749892,3.629240,25.78,...,1.384438,0.755842,0.325354,0.119390,0.056951,0.062667,0.098769,0.146215,0.184803,0.196689
41,Train-42,20.76,CCCCCCc2c(CCCCCC)c(c1cccc(OC)c1)sc2c3ccc(C(=O)...,492.725,4,0,9.12290,0.269112,5.146173,35.53,...,1.635836,1.974697,1.866746,1.399961,0.869828,0.510805,0.368140,0.373142,0.442061,0.503521

In [67]:
print(X.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42 entries, 0 to 41
Columns: 144 entries, Mass to Smiles_encoded
dtypes: float64(137), int32(1), int64(6)
memory usage: 47.2 KB
None